---
- name: create project
  os_project:
    cloud: ansible
    state: present
    name: '{{ projectName }}' 
    enabled: true

- name: create user
  os_user:
    cloud: ansible
    state: present
    name: '{{ userName }}'
    password: '{{ userPassword }}'
    default_project: '{{ projectName }}'

- name: create network
  os_network: 
    cloud: '{{ projectName }}'
    state: present 
    name: linque_net

- name: create subnet 
  os_subnet: 
    cloud: '{{ projectName }}'
    name: linque_subnet
    network_name: linque_net
    cidr: 10.0.0.0/24 
    dns_nameservers: 8.8.8.8 
    state: present 

- name: create router 
  os_router: 
    cloud: '{{ projectName }}'
    name: linque_router
    state: present 
    network: public
    interfaces: 
      - linque_subnet

- name: create security group 
  os_security_group: 
    cloud: '{{ projectName }}'
    state: present 
    name: linuque-sg

- name: add security group rule 
  os_security_group_rule: 
    cloud: '{{ projectName }}'
    state: present 
    security_group: linuque-sg
    protocol: tcp 
    port_range_min: 22 
    port_range_max: 22 
    remote_ip_prefix: 0.0.0.0/0 

- name: create keypair 
  os_keypair: 
    cloud: '{{ projectName }}'
    state: present 
    name: linuque-key
  register: keypair_info 

- name: create private key 
  copy: 
    content: "{{ keypair_info['key']['private_key'] }}" 
    dest: ./gateway-to-linuqevms-key.pem 
    mode: 0600 
  when: keypair_info.changed 

- name: create instance 
  os_server: 
    cloud: '{{ projectName }}'
    state: present 
    name: quest1
    image: 46d2ff3b-ae9f-491c-b57c-aa6f087c6cb9
    flavor: t1.linuxDefault
    key_name: linuque-key
    security_groups: linuque-sg
    network: linque_net
    floating_ip_pools: public
